name: Linter

on:
  workflow_call:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - name: Python flake8 Lint
      uses: py-actions/flake8@v2.3.0
      with:
        ignore: E501,W605
