name: Pipeline

on: [push]

permissions:
  actions: read
  contents: read
  statuses: read
  security-events: write

jobs:
  run-setup:
    name: SetUp
    uses: ./.github/workflows/setup.yml
  run-linter:
    needs: run-setup
    name: Lint
    uses: ./.github/workflows/lint_yaml.yml
  # run-testing:
  #   name: PyTest
  #   uses: ./.github/workflows/pytest.yml
  run-snyk:
    name: Snyk
    uses: ./.github/workflows/snyk.yml