name: Pipeline

on: [push]

permissions: read-all

jobs:
  run-setup:
    name: SetUp
    uses: ./.github/workflows/setup.yml
  run-linter:
    needs: run-setup
    name: Lint
    uses: ./.github/workflows/lint_yaml.yml
  run-testing:
    name: PyTest
    uses: ./.github/workflows/pytest.yml