name: Pipeline

on: [push]

permissions:
  security-events: write
  actions: read
  attestations: read
  checks: read
  contents: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  statuses: read
  id-token: none

jobs:
  run-setup:
    name: SetUp
    uses: ./.github/workflows/setup.yml
  run-linter:
    needs: run-setup
    name: Lint
    uses: ./.github/workflows/lint_yaml.yml
  # run-testing:
  #   name: PyTest
  #   uses: ./.github/workflows/pytest.yml
  # run-snyk:
  #   needs: run-setup
  #   name: Snyk
  #   uses: ./.github/workflows/snyk.yml
  security:
    needs: run-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}