name: Pipeline

on: [push]

permissions: read-all

jobs:
  run-linter:
    name: Lint
    uses: ./.github/workflows/lint_yaml.yml
  run-testing:
    name: PyTest
    uses: ./.github/workflows/pytest.yml