name: Snyk

on:
  workflow_call:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  statuses: read
  security-events: write

  jobs:
  security:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
